FROM docker.io/library/node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG REACT_APP_SIMFRETE_API_BASE_URL=/
ARG REACT_APP_UNIMED_API_BASE_URL=/api/unimed/

ENV REACT_APP_SIMFRETE_API_BASE_URL=$REACT_APP_SIMFRETE_API_BASE_URL
ENV REACT_APP_UNIMED_API_BASE_URL=$REACT_APP_UNIMED_API_BASE_URL

RUN npm run build

FROM docker.io/library/nginx:1.27-alpine

COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
